name: mypethub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  animate_do: ^3.3.4
  flutter_launcher_icons: ^0.14.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter_onboarding_slider: ^1.0.11
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  google_nav_bar: ^5.0.7
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: 'assets/dog-nose.png'
  android: true
  ios: true
