name: mypethub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  animate_do: ^3.3.4
  flutter_launcher_icons: ^0.14.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter_onboarding_slider: ^1.0.11
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  google_nav_bar: ^5.0.7
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.10.0
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  awesome_snackbar_content: ^0.1.4
  http: ^1.2.2
  webview_flutter: ^4.10.0
  firebase_messaging: ^15.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: 'assets/dog-nose.png'
  android: true
  ios: true
