// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC002VEcRSC6tSWaLAP5vK3JISE6SEhEY8',
    appId: '1:921492009974:web:40d490a3cc8e6f2c724dd7',
    messagingSenderId: '921492009974',
    projectId: 'mypethub-9ddfa',
    authDomain: 'mypethub-9ddfa.firebaseapp.com',
    storageBucket: 'mypethub-9ddfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6XUX6vrj3UlPo0go_XxkndW2PYFpAn1Q',
    appId: '1:921492009974:android:3187bd18f358d6e2724dd7',
    messagingSenderId: '921492009974',
    projectId: 'mypethub-9ddfa',
    storageBucket: 'mypethub-9ddfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfsZAUWDStaZ3iDubgVV1pvfbl-Yxxaw',
    appId: '1:921492009974:ios:441262d3fe8d78df724dd7',
    messagingSenderId: '921492009974',
    projectId: 'mypethub-9ddfa',
    storageBucket: 'mypethub-9ddfa.firebasestorage.app',
    iosBundleId: 'com.example.mypethub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzfsZAUWDStaZ3iDubgVV1pvfbl-Yxxaw',
    appId: '1:921492009974:ios:441262d3fe8d78df724dd7',
    messagingSenderId: '921492009974',
    projectId: 'mypethub-9ddfa',
    storageBucket: 'mypethub-9ddfa.firebasestorage.app',
    iosBundleId: 'com.example.mypethub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC002VEcRSC6tSWaLAP5vK3JISE6SEhEY8',
    appId: '1:921492009974:web:d3d5a63ea16b574f724dd7',
    messagingSenderId: '921492009974',
    projectId: 'mypethub-9ddfa',
    authDomain: 'mypethub-9ddfa.firebaseapp.com',
    storageBucket: 'mypethub-9ddfa.firebasestorage.app',
  );
}
